name       : kimageformats
version    : 5.92.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kimageformats-5.92.0.tar.xz : ce049989125a49dc9bf8d2a2f2f5a2fec79e25a6343087b024fefd0131eca369
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - karchive-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
