name       : kimageformats
version    : 5.82.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/kimageformats-5.82.0.tar.xz : 3e7852b85f2a2e5d7136548747b5fd75b8c81e99c9f691bb8a168ce72bb1057d
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
