name       : kimageformats
version    : 5.107.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/kimageformats-5.107.0.tar.xz : 97258ad36bf98cd1aaeeb29c49946031f5051d9984bda9f41fda5a35ccd4d1c1
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - pkgconfig(libraw)
    - karchive-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
