name       : kimageformats
version    : 5.106.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kimageformats-5.106.0.tar.xz : fb3f3e8aeb97fcf35151787a5ccab4938d4d711415cc5be9d61d768c32790e8f
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - pkgconfig(libraw)
    - karchive-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
