name       : kimageformats
version    : 5.100.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kimageformats-5.100.0.tar.xz : cbb5253d55c0ac09689b772f0723a42c290e8df3448116f556f5d320c6738827
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - pkgconfig(libraw)
    - karchive-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
