name       : kimageformats
version    : 5.78.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kimageformats-5.78.0.tar.xz : ecd4cf4ec006998b73724776cb2cb11f636057bd5f29ae134451fec612e1623f
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
