name       : kimageformats
version    : 5.74.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kimageformats-5.74.0.tar.xz : 732c94512a26ff4c4fcdea46ce26fcd7c700c129188c181115fbb0facac937fe
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - GPL-2.0-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
