name       : kimageformats
version    : 5.76.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kimageformats-5.76.0.tar.xz : 78ced2665f8918beb617b74962d188dcbb01a92a90ba49bfd173671bdb14e68d
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
