name       : kimageformats
version    : 5.80.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kimageformats-5.80.0.tar.xz : 1d65641583e44c25de8ac98d7ef5925f08074a9ccf33ef7e7b504dd3a7347160
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
