name       : kimageformats
version    : 5.96.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kimageformats-5.96.0.tar.xz : a5ce354ef2d0146609e0a681e74da078b0592195e304d45670e5e698d5167435
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - karchive-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
