name       : kimageformats
version    : 5.109.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kimageformats-5.109.0.tar.xz : 15533e1ba0fa187f0da0094b8ea135f38a9cebffd9118a12fcd23003eb591687
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - pkgconfig(libraw)
    - karchive-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
