name       : kimageformats
version    : 5.81.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kimageformats-5.81.0.tar.xz : a332a0d708417c6e973b19d8b3aec006f3c1c57ef17851dc00e4921d7c43864e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
