name       : kimageformats
version    : 5.83.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kimageformats-5.83.0.tar.xz : dc3965efbf9f2a42b78bbaea3d825b0946a27ad5fc79395cd405c858f38d8917
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : multimedia.graphics
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DKIMAGEFORMATS_HEIF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
